using Content.Client.UserInterface.Controls;
using Content.Shared.Arcade.Enums;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.UI;

/// <summary>
///
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class BlockGameArcadeWindow : FancyWindow
{
    /// <summary>
    ///
    /// </summary>
    private static readonly Vector2i CellSize = new(32, 32);

    /// <summary>
    ///
    /// </summary>
    public event Action<BlockGameArcadeAction>? OnAction;

    /// <summary>
    ///
    /// </summary>
    private StyleBoxFlat[] _cells = [];

    /// <summary>
    ///
    /// </summary>
    private bool _usability = true;

    public BlockGameArcadeWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (!_usability || args.Handled)
            return;

        if (args.Function == ContentKeyFunctions.ArcadeDown)
        {
            OnAction?.Invoke(BlockGameArcadeAction.Down);
            args.Handle();
        }
        else if (args.Function == ContentKeyFunctions.ArcadeLeft)
        {
            OnAction?.Invoke(BlockGameArcadeAction.Left);
            args.Handle();
        }
        else if (args.Function == ContentKeyFunctions.ArcadeRight)
        {
            OnAction?.Invoke(BlockGameArcadeAction.Right);
            args.Handle();
        }
        else if (args.Function == ContentKeyFunctions.ArcadeDrop)
        {
            OnAction?.Invoke(BlockGameArcadeAction.Drop);
            args.Handle();
        }
        else if (args.Function == ContentKeyFunctions.ArcadeRotate)
        {
            OnAction?.Invoke(BlockGameArcadeAction.Rotate);
            args.Handle();
        }
    }

    /// <summary>
    ///
    /// </summary>
    public void SetUsability(bool value)
    {
        _usability = value;
    }

    /// <summary>
    ///
    /// </summary>
    public void CreateGrid(int gridWidth, Color[] grid)
    {
        Grid.Columns = gridWidth;

        if (_cells.Length == grid.Length)
        {
            for (var i = 0; i < grid.Length; i++)
                _cells[i].BackgroundColor = grid[i];

            return;
        }

        _cells = new StyleBoxFlat[grid.Length];
        Grid.RemoveAllChildren();

        for (var i = 0; i < grid.Length; i++)
        {
            var cell = new StyleBoxFlat
            {
                BackgroundColor = grid[i],
            };

            Grid.AddChild(new PanelContainer
            {
                PanelOverride = cell,
                MinSize = CellSize,
            });

            _cells[i] = cell;
        }
    }

    /// <summary>
    ///
    /// </summary>
    public void UpdateGridCell(int index, Color newColor)
    {
        _cells[index].BackgroundColor = newColor;
    }
}
